{
 "title": "Production Data",
 "description": "Terminal Name metric",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "telegramnamevar",
    "label": "Telegram Type",
    "query": "select name from telegram_types where name<>'LIFE_BEAT'"
   },
   {
    "name": "terminalnamevar",
    "label": "Terminal Name",
    "query": "select terminal_name from ec_terminal_mapping union select 'unknown'"
   },
   {
    "name": "requesttype",
    "label": "Protocol",
    "query": "select 'xml' union select 'txt'"
   }
  ]
 },
 "panels": [
  {
   "title": "Response times - Message Type metric",
   "type": "graph",
   "gridPos": { "h": 21, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "response time" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  request_log_timestamp AS \"time\",\n  case when extract(epoch from response_delay)>10 then 10 else extract(epoch from response_delay) end,\n  coalesce(telegram_name_var,'UNKNOWN') as metric\nFROM telegram_ui_table\nWHERE\n  $__timeFilter(request_log_timestamp) \n  AND \"request_type\" in ($requesttype)\n  AND \"telegram_name_var\" in ($telegramnamevar)\n  AND \"terminal_name_var\" in ($terminalnamevar)\n  AND extract(epoch from response_delay) < 300\nORDER BY 1,3"
    },
    {
     "rawSql": "WITH RECURSIVE  dates(var1, var2) as(\r\n\tVALUES(TO_TIMESTAMP($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS') + INTERVAL '1 hour', TO_TIMESTAMP($__timeTo(),'YYYY-MM-DDTHH24:MI:SS') + INTERVAL '2 hour')\r\n),\r\ntheDATES AS(\r\n\tSELECT dates.var1 as theDate\r\n\tFROM dates\r\n\tUNION ALL \r\n\tSELECT theDate + INTERVAL '1 Minute'\r\n\tFROM theDATES, dates\r\n\tWHERE theDate + INTERVAL '1 Minute' <= dates.var2\r\n),\r\ntheValue(ertek,dates) as(\r\nSELECT COUNT(*) as ertek, make_timestamp(extract(year from request_log_timestamp)::int,extract(month from request_log_timestamp)::int, extract(day from request_log_timestamp)::int, extract(hour from request_log_timestamp)::int, extract(minute from request_log_timestamp)::int,0::int) as timei\r\nFROM telegram_ui_table\r\nWHERE $__timeFilter(request_log_timestamp) and\r\ntelegram_name_var IN ($telegramnamevar)\r\nGROUP BY make_timestamp(extract(year from request_log_timestamp)::int,extract(month from request_log_timestamp)::int, extract(day from request_log_timestamp)::int, extract(hour from request_log_timestamp)::int, extract(minute from request_log_timestamp)::int,0)\r\n)\r\n\r\nSELECT theDate as time, COALESCE(theValue.ertek,0) as value\r\nFROM theDATES\r\nLEFT join theValue\r\non make_timestamp(extract(year from theDate)::int,extract(month from theDate)::int, extract(day from theDate)::int, extract(hour from theDate)::int, extract(minute from theDate)::int,0) = theValue.dates\r\nORDER BY theDate"
    }
   ]
  },
  {
   "title": "AVO_END average",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  telegram_name_var AS \"Message Type\",\n  --count(*) as \"Count\",\n  avg(extract(epoch from response_delay)) as \"Average\"\nFROM telegram_ui_table\nWHERE\n  $__timeFilter(request_log_timestamp) \n  AND \"request_type\" in ($requesttype)\n  AND \"telegram_name_var\" = 'AVO_END'\n  AND \"terminal_name_var\" in ($terminalnamevar)\n  AND extract(epoch from response_delay) < 300\nGROUP BY telegram_name_var\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Response time averages",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  telegram_name_var AS \"Message Type\",\n  count(*) as \"Count\",\n  avg(extract(epoch from response_delay)) as \"Average\"\nFROM telegram_ui_table\nWHERE\n  $__timeFilter(request_log_timestamp) \n  AND \"request_type\" in ($requesttype)\n  AND \"telegram_name_var\" in ($telegramnamevar)\n  AND \"terminal_name_var\" in ($terminalnamevar)\n  AND extract(epoch from response_delay) < 300\nGROUP BY telegram_name_var\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as \"Number of telegrams\",\n  avg(extract(epoch from response_delay)) as \"Average\"\nFROM telegram_ui_table\nWHERE\n  $__timeFilter(request_log_timestamp) \n  AND \"request_type\" in ($requesttype)\n  AND \"telegram_name_var\" in ($telegramnamevar)\n  AND \"terminal_name_var\" in ($terminalnamevar)\n  AND extract(epoch from response_delay) < 300\nORDER BY 1"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 20 },
   "targets": [
    {
     "rawSql": "WITH RECURSIVE  dates(var1, var2) as(\r\n\tVALUES(TO_TIMESTAMP($__timeFrom(),'YYYY-MM-DDTHH24:MI:SS') + INTERVAL '2 hour', TO_TIMESTAMP($__timeTo(),'YYYY-MM-DDTHH24:MI:SS') + INTERVAL '2 hour')\r\n\t--  + INTERVAL '2 hour' has to be set to the timezone IN CASE OF (UTC +02:00) is should be  + INTERVAL '2 hour'\r\n),\r\ntheDATES AS(\r\n\tSELECT dates.var1 as theDate\r\n\tFROM dates\r\n\tUNION ALL \r\n\tSELECT theDate + INTERVAL '1 Minute'\r\n\tFROM theDATES, dates\r\n\tWHERE theDate + INTERVAL '1 Minute' <= dates.var2\r\n),\r\ntheValue(ertek,dates) as(\r\nSELECT COUNT(*) as ertek, make_timestamp(extract(year from request_log_timestamp)::int,extract(month from request_log_timestamp)::int, extract(day from request_log_timestamp)::int, extract(hour from request_log_timestamp)::int, extract(minute from request_log_timestamp)::int,0::int) as timei\r\nFROM telegram_ui_table\r\nWHERE $__timeFilter(request_log_timestamp) and\r\ntelegram_name_var IN ($telegramnamevar)\r\nGROUP BY make_timestamp(extract(year from request_log_timestamp)::int,extract(month from request_log_timestamp)::int, extract(day from request_log_timestamp)::int, extract(hour from request_log_timestamp)::int, extract(minute from request_log_timestamp)::int,0)\r\n)\r\n\r\nSELECT 'Average telegram count:' as Text ,(AVG((theValue.ertek)::int))::int as value\r\nFROM theDATES\r\nLEFT join theValue\r\non make_timestamp(extract(year from theDate)::int,extract(month from theDate)::int, extract(day from theDate)::int, extract(hour from theDate)::int, extract(minute from theDate)::int,0) = theValue.dates"
    }
   ]
  },
  {
   "title": "SIT-BC Backlog History",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATEADD(HOUR,-2,RowUpdated) AS 'time', MessageCount AS 'value',  CASE WHEN MessageCount > 2500 THEN MessageCount ELSE NULL END AS 'warning',  CASE WHEN MessageCount > 5000 THEN MessageCount ELSE NULL END AS 'error'\nFROM VES2PTS1.dbo.BarflowMessage\nWHERE RowUpdated BETWEEN DATEADD(HOUR,+2,$__timeFrom()) and DATEADD(HOUR,+2,$__timeTo())\n--WHERE $__timeFilter(RowUpdated)"
    }
   ]
  },
  {
   "title": "DIS Connector SIT-BC Backlog",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT MESSAGE_TYPE, COUNT(MESSAGE_TYPE) as 'count' FROM [ARCH_T_SitMesComponentRT1A8997AF-5067-47d5-80DB-AF14C4BD2402/EC_SAP_TRANSFER_$118$] nolock\nWHERE SENT = 0 and MESSAGE_TYPE in ('GOODS_RECEIPT', 'GOODS_MOVEMENT', 'BACKFLUSH')\nGROUP BY MESSAGE_TYPE\nOPTION (MAXDOP 1)\n"
    }
   ]
  },
  {
   "title": "WhoIsActive DB Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATEADD(HOUR, -2, [collection_time]) AS time, \r\n(\t\r\n\tCAST(LEFT(RIGHT([dd hh:mm:ss.mss], 12),2) AS float)*3600 \r\n\t+ CAST(LEFT(RIGHT([dd hh:mm:ss.mss], 9),2) AS float)*60 \r\n\t+ CAST(RIGHT([dd hh:mm:ss.mss], 6) AS float)\r\n) AS 'Running time (s)'\r\n, [login_name]\r\nFROM [DBMaintenance].[dbo].[WhoIsActive] (NOLOCK)\r\nWHERE $__timeFrom() < DATEADD(HOUR, -2, [collection_time])\r\nAND $__timeTo() > DATEADD(HOUR, -2, [collection_time])\r\nand [dd hh:mm:ss.mss] != '00 00:00:03.000'\r\nand [dd hh:mm:ss.mss] != '00 00:00:06.000'\r\nand [dd hh:mm:ss.mss] != '00 00:00:00.000'\r\nOPTION (MAXDOP 1)"
    },
    {
     "rawSql": "SELECT DATEADD(HOUR, -2, [collection_time]) AS time, \r\n(\t\r\n\tCAST(LEFT(RIGHT([dd hh:mm:ss.mss], 12),2) AS float)*3600 \r\n\t+ CAST(LEFT(RIGHT([dd hh:mm:ss.mss], 9),2) AS float)*60 \r\n\t+ CAST(RIGHT([dd hh:mm:ss.mss], 6) AS float)\r\n) AS 'Running time (s)'\r\n, CONCAT( [login_name], '  Blocking ID: ', [blocking_session_id] )\r\nFROM [DBMaintenance].[dbo].[WhoIsActive] (NOLOCK)\r\nWHERE $__timeFrom() < DATEADD(HOUR, -2, [collection_time])\r\nAND $__timeTo() > DATEADD(HOUR, -2, [collection_time])\r\nAND blocking_session_id is not null\r\nOPTION (MAXDOP 1)"
    }
   ]
  }
 ]
}